### PR TITLE
Implemented the authetication feature

### LINKED ISSUE #25: Backend: Registration API
User Story:
As a developer, I want to create an API endpoint for user registration so that new users can create accounts in the system.
Description:
Implement the API endpoint using Node.js and Express to handle registration requests. Validate the incoming data, hash the password, and store the user information securely in the MySQL database. Return appropriate responses based on success or failure.
Acceptance Criteria:
The API must validate incoming requests (check for required fields and validate email format).
Passwords must be hashed securely before storing them in the database.
The API should check if the email already exists and return an error message if it does.
On successful registration, the API should return a success status and message.

### LINKED ISSUE #27: Backend: Login API
User Story:	
As a developer, I want to implement an API endpoint for user login so that users can authenticate and access their accounts.
Description:
Develop an API endpoint using Node.js and Express for handling login requests. Validate the user’s credentials, compare passwords, and return a session token or JWT if authentication is successful.
Acceptance Criteria:
The API should verify the provided email and password against stored values in the database.
On successful authentication, a session token or JWT must be generated and returned to the client.
If credentials are invalid, the API should return an appropriate error message.
The API should use HTTPS for secure communication.

### LINKED ISSUE #31: Backend: Profile Management API
User Story:
As a developer, I want to build an API endpoint for profile management so that users can update their information in the database.
Description:
Implement the profile management API using Node.js and Express. The endpoint should handle GET requests to retrieve user data and POST/PUT requests to update the information. Ensure data validation and security measures are in place.
Acceptance Criteria:
The API must provide a GET endpoint that returns the user’s profile data.
The API should provide a POST/PUT endpoint to update user data, validating fields before saving to the database.
On successful update, the API must return a success status and updated user information.
If an update fails, an appropriate error message should be returned.

### LINKED ISSUE #33: Backend: Logout API
User Story:
As a developer, I want to implement a logout API endpoint so that user sessions can be securely terminated.
Description:
Create the logout endpoint using Node.js and Express to invalidate the user’s session or token. Ensure that the session is removed from the database or server-side cache, and return a response confirming the action.
Acceptance Criteria:
The API must terminate the user’s session or invalidate the JWT token.
A success response should be returned to the frontend upon successful logout.
Any attempt to use the invalidated session/token should be rejected by the API.

### PR DESCRIPTION
**Pull request by OreLana**
**What does this PR do?**

Build out the authentication feature for the hire-wire

**List of task completed**

-   [x] Resolved the duplicate, models, routes, controller files
-  [x] Built the User model 
-  [x] Implemented the routes for the user(register, login, logout, update, view, delete)
-  [x] Built the controllers to handle each of the logic for the user routes
-  [x] Installed the passport plugin to help with authentication and validation

**How can this be tested?**
How can this be tested?

-  Pull these changes:
-  Ensure your database connection is up to date
- Install dependencies using `npm install`
-  Run `npx sequelize-cli db:migrate` to create the User table in your database
-  Run `npm start ` to start the application
-  Go to your web browser and enter http://localhost:8000/

- Highlight how this PR can be tested

Run `npm test`

**Additional info**

Add more info if any. eg fixes #.

### CODE REVIEW

**Comment by lflanagan7** [comment]
When I start the application and go to the browser it displays this: {"message": "Route not found"} 
When I run npm test I am getting an error due to the import.meta line in the index.js model file. This is the full error message: 
> hire-wire@1.0.0 test
> jest

 FAIL  tests/app.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

/hire-wire/src/models/index.js:22
    var basename = _path["default"].basename((0, _url.fileURLToPath)(import.meta.url));
                                                                            ^^^^

    SyntaxError: Cannot use 'import.meta' outside a module

      1 | // src/config/passport.js
      2 | import { Strategy as JwtStrategy, ExtractJwt } from 'passport-jwt';
    > 3 | import db from '../models/index.js'; // Adjust this path based on your project structure
        | ^
      4 |
      5 | const passportConfig = (passport) => {
      6 |   // Define options for JWT strategy

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.require (src/config/passport.js:3:1)
      at Object.require (server.js:6:1)
      at Object.require (tests/app.test.js:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.481 s
Ran all test suites.

**Comment by stevenhcau** [comment]
So I'm having a different problem. I am unable to start using `npm start`. I believe my issue has something to do with being on a Windows computer, and it not being able to resolve my D:\ drive. I did some searching and troubleshooting but I have not been able to get the server to start properly. My thought is that is has something to do with the `.config`, and `module.export`.

```
PS D:\GitHub\hire-wire> npm start

> hire-wire@1.0.0 start
> node server.js
`

node:internal/modules/esm/load:227
    throw new ERR_UNSUPPORTED_ESM_URL_SCHEME(parsed, schemes);
          ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:227:11)
    at defaultLoad (node:internal/modules/esm/load:109:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:666:12)
    at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:479:43)
    at #createModuleJob (node:internal/modules/esm/loader:503:36)
    at #getJobFromResolveResult (node:internal/modules/esm/loader:274:34)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:41)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:542:25) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

Node.js v22.11.0
```

Edit: I have tested on two different devices and I am having the same error on both my Windows PC and laptop

**Comment by OreLana** [comment]
All tests have been fixed locally and are now passing on github.

**Review by lflanagan7 — APPROVED** [review]
confirmed test passes for me

**Pull request merged**
